version: '2'

services:
  django-develoment:
      build:
        context: .
        dockerfile: Dockerfile-Django
      volumes:
        - ./backend:/rappi_project/backend
      working_dir: /rappi_project/backend/

  node-develoment:
      build:
        context: .
        dockerfile: Dockerfile-Node
      volumes:
        - ./frontend:/rappi_project/frontend
      working_dir: /rappi_project/frontend